#spring:
#  # 数据库配置
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mushroom?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 最小闲置数
#      min-idle: 10
#      # 最大活动数
#      max-active: 100
#      # 初始化内存
#      initial-size: 20
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#
#  thymeleaf:
#    prefix: classpath:/templates/
#    cache: false
#    encoding: UTF-8
#    mode: HTML5
#    suffix: .html
#
## JPA 的数据库类生成配置，重置数据库使用。
##  jpa:
##    hibernate:
##      ddl-auto: update
##    # MYSQL8 需要增加
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
## Mybatis 配置（需要将 XML 文件移植至 resouces 目录下）
#mybatis-plus:
#  type-aliases-package: com.myself.gzkemays.pojo
#  mapper-locations: classpath:xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
